#ifndef PROTOTYOPES_H_INCLUDED
#define PROTOTYOPES_H_INCLUDED


#include <stdio.h>
#include <stdlib.h>
#include <allegro.h>
#include <time.h>
#include <string.h>

void creation_icones_classes();
void reperage_bloc_souris();
void reperage_chemin();
void lecture_pixels_buffer_map();
void sleep();
void deplacement_nombre_pm();
void display_cursor();
void choix_classe();
void creation_classes();
void deplacement_joueur();
void tour_joueur();
int menu();
void quadrillage_test();
void distribution_couleur_blocs();
void definition_accessible();
void definition_occuper();
void deplacement_personnage();
void affichage_croix_bleue();
void affichage_croix_rouge();
void dessin_bloc_unique();
void usleep();
void zone_max_deplacement_0pm();
void zone_max_deplacement_1pm();
void zone_max_deplacement_2pm();
void zone_max_deplacement_3pm();
void anomalie_case_deplacement();
void affichage_general();
void affichage_joueurs();
void animation_deplacement();
void affichage_emplacement_depart();
void condition_positionnement_depart();
void couleur_sous_joueur();
void selection_sort();
void sort1_guerrier();
void sort2_guerrier();
void sort3_guerrier();
void sort4_guerrier();
void sort1_mage();
void sort2_mage();
void sort3_mage();
void sort4_mage();
void sort1_vampire();
void sort2_vampire();
void sort3_vampire();
void sort4_vampire();
void sort1_assassin();
void sort2_assassin();
void sort3_assassin();
void sort4_assassin();
void dessin_ligne();
void dessin_diagonales();
void animation_attaque_de_base();
void affichage_autres_joueurs();
void affichage_hud_sorts();
void affichage_hud_joueur();

#endif // PROTOTYOPES_H_INCLUDED
